version: '2.1'
services:
  server:
    build:
      context: .
      dockerfile: ./Dockerfile
      args:
        version: 7-apache
    volumes:
      - ./config:/var/www/config
      - ./html:/var/www/html
      - ./src:/var/www/src
      - ./templates:/var/www/templates
    ports:
      - 80:80
