'POST /application':
  path: /applications
  handler: MatthiasMullie\ApiOauth\Controllers\Application\Post
  methods:
    POST:
      query:
        access_token:
          description: Unique access code
          type: sha1
          required: true
          scope: [root]
      form_params:
        application:
          description: Unique application name
          type: string
          required: true
          scope: [root]
      responses:
        application:
          description: Unique application name
          type: string
          scope: [root]
        client_id:
          description: Public client id of the application
          type: sha1
          scope: [root]
        client_secret:
          description: Secret client id of the root application (do not give out!)
          type: sha1
          scope: [root]
        user_id:
          description: User id of the application's owner
          type: sha1
          scope: [root]

'GET /application/{client_id}':
  path: /applications/{client_id}
  handler: MatthiasMullie\ApiOauth\Controllers\Application\Get
  methods:
    GET:
      query:
        access_token:
          description: Unique access code
          type: sha1
          required: true
          scope: [root]
      form_params:
      responses:
        application:
          description: Unique application name
          type: string
        client_id:
          description: Public client id of the application
          type: sha1
        client_secret:
          description: Secret client id of the root application (do not give out!)
          type: sha1
          scope: [root]
        user_id:
          description: User id of the application's owner
          type: sha1

'PUT /application/{client_id}':
  path: /applications/{client_id}
  handler: MatthiasMullie\ApiOauth\Controllers\Application\Put
  methods:
    PUT:
      query:
        access_token:
          description: Unique access code
          type: sha1
          required: true
          scope: [root]
      form_params:
        application:
          description: Unique application name
          type: string
          required: true
          scope: [root]
        user_id:
          description: Unique user id of the owner of the application
          type: sha1
          required: true
          scope: [root]
      responses:
        application:
          description: Unique application name
          type: string
          scope: [root]
        client_id:
          description: Public client id of the application
          type: sha1
          scope: [root]
        client_secret:
          description: Secret client id of the root application (do not give out!)
          type: sha1
          scope: [root]
        user_id:
          description: User id of the application's owner
          type: sha1
          scope: [root]

'PATCH /application/{client_id}':
  path: /applications/{client_id}
  handler: MatthiasMullie\ApiOauth\Controllers\Application\Patch
  methods:
    PATCH:
      query:
        access_token:
          description: Unique access code
          type: sha1
          required: true
          scope: [root]
      form_params:
        application:
          description: Unique application name
          type: string
          scope: [root]
        user_id:
          description: Unique user id of the owner of the application
          type: sha1
          scope: [root]
      responses:
        application:
          description: Unique application name
          type: string
          scope: [root]
        client_id:
          description: Public client id of the application
          type: sha1
          scope: [root]
        client_secret:
          description: Secret client id of the root application (do not give out!)
          type: sha1
          scope: [root]
        user_id:
          description: User id of the application's owner
          type: sha1
          scope: [root]

'DELETE /application/{client_id}':
  path: /applications/{client_id}
  handler: MatthiasMullie\ApiOauth\Controllers\Application\Delete
  methods:
    DELETE:
      query:
        access_token:
          description: Unique access code
          type: sha1
          required: true
          scope: [root]

'GET /authorize':
  path: /authorize
  handler: MatthiasMullie\ApiOauth\Controllers\Authorize\Get
  methods:
    GET:
      query:
        client_id:
          description: Public client id of the application to authorize with
          type: sha1
          required: true
        redirect_uri:
          description: URI to redirect to after successful authorization (code will be appended)
          type: url
          required: true
        scope:
          description: Comma-separated list of scopes to subscribe to
          type: string
          required: true
      form_params:
      responses:
        status_code:
          description: HTTP status code
          type: int
        headers:
          description: Response headers
          type: array
        body:
          description: HTML body
          type: string

'POST /authorize':
  path: /authorize
  handler: MatthiasMullie\ApiOauth\Controllers\Authorize\Post
  methods:
    POST:
      query:
        client_id:
          description: Public client id of the application to authorize with
          type: sha1
          required: true
        redirect_uri:
          description: URI to redirect to after successful authorization (code will be appended)
          type: url
          required: true
      form_params:
        email:
          description: Email address of the user authorizing
          type: email
          required: true
        password:
          description: Password of the user authorizing
          type: string
          required: true
        nonce:
          description: Unique hash only valid once, to ensure this form can't be submitted by outside parties
          type: sha512
          required: true
      responses:
        status_code:
          description: HTTP status code
          type: int
        headers:
          description: Response headers
          type: array
        body:
          description: HTML body
          type: string

'POST /login':
  path: /login
  handler: MatthiasMullie\ApiOauth\Controllers\Login\Post
  methods:
    POST:
      query:
      form_params:
        client_id:
          description: Public client id of the root application
          type: sha1
          required: true
        client_secret:
          description: Secret client id of the root application (do not give out!)
          type: sha1
          required: true
        email:
          description: Email address of the user logging in
          type: email
          required: true
        password:
          description: Password of the user logging in
          type: string
          required: true
      responses:
        code:
          description: Unique code to authenticate an application-user relationship
          type: sha1

'POST /authenticate':
  path: /authenticate
  handler: MatthiasMullie\ApiOauth\Controllers\Authenticate\Post
  methods:
    POST:
      query:
      form_params:
        code:
          description: Authorization code
          type: sha1
        refresh_token:
          description: Refresh token
          type: sha1
        client_id:
          description: Public client id of the application to authenticate with
          type: sha1
          required: true
        client_secret:
          description: Secret client id of the application to authenticate with (do not give out!)
          type: sha1
          required: true
        grant_type:
          description: The type of token to obtain (authorization_code or refresh_token)
          type: string
          required: true
      responses:
        access_token:
          description: Unique code identifying an application-user relationship, required to access/update relevant data
          type: sha1
        issued_at:
          description: Timestamp when access_token was issued
          type: int
        expires_in:
          description: Amount of seconds left until access_token expires
          type: int
        refresh_token:
          description: Unique code to generate a new access_token when the previous one has expired
          type: sha1
        scope:
          description: Scopes that have been authenticated
          type: array

'POST /users':
  path: /users
  handler: MatthiasMullie\ApiOauth\Controllers\User\Post
  methods:
    POST:
      query:
      form_params:
        client_id:
          description: Public client id of the root application
          type: sha1
          required: true
        client_secret:
          description: Secret client id of the root application (do not give out!)
          type: sha1
          required: true
        email:
          description: New email address of the user
          type: email
          required: true
        password:
          description: New password of the user
          type: string
          required: true
      responses:
        user_id:
          description: Unique user id
          type: sha1
        email:
          description: Email address of the user
          type: email
        access_token:
          description: Unique code identifying the root application-user relationship, required to access/update relevant data
          type: sha1
        issued_at:
          description: Timestamp when access_token was issued
          type: int
        expires_in:
          description: Amount of seconds left until access_token expires
          type: int
        refresh_token:
          description: Unique code to generate a new access_token when the previous one has expired
          type: sha1
        scope:
          description: Scopes that have been authenticated
          type: array

'GET /users/{user_id}':
  path: /users/{user_id}
  handler: MatthiasMullie\ApiOauth\Controllers\User\Get
  methods:
    GET:
      query:
        access_token:
          description: Unique access code
          type: sha1
      form_params:
      responses:
        user_id:
          description: Unique user id
          type: sha1
        email:
          description: Email address of the user
          type: email
          scope: [root, private]

'PUT /users/{user_id}':
  path: /users/{user_id}
  handler: MatthiasMullie\ApiOauth\Controllers\User\Put
  methods:
    PUT:
      query:
        access_token:
          description: Unique access code
          type: sha1
          required: true
          scope: [root, private]
      form_params:
        email:
          description: New email address of the user
          type: email
          required: true
          scope: [root]
        password:
          description: New password of the user
          type: string
          required: true
          scope: [root]
      responses:
        user_id:
          description: Unique user id
          type: sha1
        email:
          description: Email address of the user
          type: email
          scope: [root, private]

'PATCH /users/{user_id}':
  path: /users/{user_id}
  handler: MatthiasMullie\ApiOauth\Controllers\User\Patch
  methods:
    PATCH:
      query:
        access_token:
          description: Unique access code
          type: sha1
          required: true
          scope: [root, private]
      form_params:
        email:
          description: New email address of the user
          type: email
          scope: [root]
        password:
          description: New password of the user
          type: string
          scope: [root]
      responses:
        user_id:
          description: Unique user id
          type: sha1
        email:
          description: Email address of the user
          type: email
          scope: [root, private]

'DELETE /users/{user_id}':
  path: /users/{user_id}
  handler: MatthiasMullie\ApiOauth\Controllers\User\Delete
  methods:
    DELETE:
      query:
        access_token:
          description: Unique access code
          type: sha1
          required: true
          scope: [root]

'GET /forgot-password':
  path: /forgot-password
  handler: MatthiasMullie\ApiOauth\Controllers\ForgotPassword\Get
  methods:
    GET:
      query:
        email:
          description: Email address to reset the password for
          type: email
          required: true

'GET /reset-password':
  path: /reset-password/{user_id}
  handler: MatthiasMullie\ApiOauth\Controllers\ResetPassword\Get
  methods:
    GET:
      query:
        access_token:
          description: Unique access code
          type: sha1
          required: true
          scope: [reset-password]
      responses:
        body:
          description: HTML body
          type: string

'POST /reset-password':
  path: /reset-password/{user_id}
  handler: MatthiasMullie\ApiOauth\Controllers\ResetPassword\Post
  methods:
    POST:
      query:
        access_token:
          description: Unique access code
          type: sha1
          required: true
          scope: [reset-password]
      form_params:
        password:
          description: New password of the user
          type: string
          required: true
          scope: [reset-password]
      responses:
        body:
          description: HTML body
          type: string
